stages:
  - build

variables:
  WS_SRC: ./pendulum_ws/src
  WS: ./pendulum_ws

build_test_pendullum:
  image: ros:dashing
  stage: build
  before_script:
    - mkdir -p $WS_SRC
    - mv * $WS_SRC && cd WS
    - apt update && apt install -y lcov
    - "rosdep install -q -y --from-paths . --ignore-src \
     --rosdistro ${ROS_DISTRO} --as-root=apt:false || true"
    - pip3 install colcon-lcov-result
  script:
    - "colcon build --merge-install --cmake-args \
	-DCMAKE_CXX_FLAGS='-fprofile-arcs -ftest-coverage' \
	-DCMAKE_C_FLAGS='-fprofile-arcs -ftest-coverage'"
    - colcon lcov-result --initial
    - colcon test --merge-install --return-code-on-test-failure
    - colcon lcov-result --filter "test"
  coverage: /\s*lines.*:\s(\d+\.\d+\%\s\(\d+\sof\s\d+.*\))/
