language: cpp
cache: ccache
compiler: gcc

notifications:
  email:
    recipients:
      - lander.usategui@gmail.com

matrix:
  include:
    - os: linux
      dist: trusty
      services:
        - docker
      sudo:
        - required
script:
    - docker build -t pendulum .
